Replace tab & 4-space to 2-space for atmos scripts
	modified:   jobs/
	modified:   rocoto/
	modified:   scripts/
	modified:   sorc/build_*.sh
	modified:   sorc/checkout.sh
	modified:   sorc/machine-setup.sh
	modified:   sorc/nco_run.sh
	modified:   ush/

Refs: #101

diff --git a/jobs/JGEFS_ATMOS_ENSAVG_NETCDF b/jobs/JGEFS_ATMOS_ENSAVG_NETCDF
--- a/jobs/JGEFS_ATMOS_ENSAVG_NETCDF
+++ b/jobs/JGEFS_ATMOS_ENSAVG_NETCDF
@@ -4,8 +4,8 @@ echo "$(date -u) begin ${BASH_SOURCE}"
 
 set -xa
 if [[ ${STRICT:-NO} == "YES" ]]; then
-	# Turn on strict bash error checking
-	set -eu
+  # Turn on strict bash error checking
+  set -eu
 fi
 export PS4='$SECONDS + $(basename ${BASH_SOURCE})[$LINENO] '
 
@@ -73,12 +73,12 @@ export COMOUT=${COMOUT:-$(compath.py -o $NET/${ver})/${RUN}.${PDY}/$cyc}
 configs="gefs gefs_atmos_ensavg_netcdf"
 config_path=$PARMgefs
 for config in $configs; do
-    . $config_path/$config.parm
-    export err=$?
-    if [[ $err != 0 ]]; then
-        echo "FATAL ERROR in ${BASH_SOURCE}: Error while loading parm file $config_path/$config.parm"
-        exit $err
-    fi
+  . $config_path/$config.parm
+  export err=$?
+  if [[ $err != 0 ]]; then
+    echo "FATAL ERROR in ${BASH_SOURCE}: Error while loading parm file $config_path/$config.parm"
+    exit $err
+  fi
 done
 
 export COMPONENT=${COMPONENT:-atmos}
@@ -91,10 +91,10 @@ env | sort
 $HOMEgefs/scripts/exgefs_atmos_ensavg_netcdf.sh
 export err=$?
 if [[ $err == 0 ]]; then
-    echo "$job completed normally!"
+  echo "$job completed normally!"
 else
-    echo "FATAL ERROR in ${BASH_SOURCE}: $job failed!"
-    exit $err
+  echo "FATAL ERROR in ${BASH_SOURCE}: $job failed!"
+  exit $err
 fi
 #############################################################
 
diff --git a/jobs/JGEFS_ATMOS_ENSSTAT b/jobs/JGEFS_ATMOS_ENSSTAT
--- a/jobs/JGEFS_ATMOS_ENSSTAT
+++ b/jobs/JGEFS_ATMOS_ENSSTAT
@@ -4,8 +4,8 @@ echo "$(date -u) begin ${.sh.file}"
 
 set -xa
 if [[ ${STRICT:-NO} == "YES" ]]; then
-	# Turn on strict bash error checking
-	set -eu
+  # Turn on strict bash error checking
+  set -eu
 fi
 export PS4='$SECONDS + $(basename ${.sh.file})[$LINENO] '
 
@@ -56,8 +56,8 @@ setpdy.sh
 source PDY
 
 if [ ${FORECAST_SEGMENT} = lr ]; then
-    export cyc=00
-    export cycle=t${cyc}z
+  export cyc=00
+  export cycle=t${cyc}z
 fi
 
 ####################################
@@ -82,16 +82,16 @@ export COMOUT=${COMOUT:-$(compath.py -o $NET/${ver})/${RUN}.${PDY}/$cyc}
 configs="gefs gefs_prdgen gefs_ensstat"
 config_path=$PARMgefs
 for config in $configs; do
-    . $config_path/$config.parm
-    export err=$?
-    if [[ $err != 0 ]]; then
-        echo "FATAL ERROR in ${.sh.file}: Error while loading parm file $config_path/$config.parm"
-        exit $err
-    fi
+  . $config_path/$config.parm
+  export err=$?
+  if [[ $err != 0 ]]; then
+    echo "FATAL ERROR in ${.sh.file}: Error while loading parm file $config_path/$config.parm"
+    exit $err
+  fi
 done
 
 if [[ $cplchm = ".true." ]]; then
-    COMPONENT="chem"
+  COMPONENT="chem"
 fi
 export COMPONENT=${COMPONENT:-atmos}
 
@@ -103,10 +103,10 @@ env | sort
 source $HOMEgefs/scripts/exgefs_atmos_ensstat.sh
 export err=$?
 if [[ $err == 0 ]]; then
-    echo "$job completed normally!"
+  echo "$job completed normally!"
 else
-    echo "FATAL ERROR in ${.sh.file}: $job failed!"
-    exit $err
+  echo "FATAL ERROR in ${.sh.file}: $job failed!"
+  exit $err
 fi
 #############################################################
 
diff --git a/jobs/JGEFS_ATMOS_GEMPAK_META b/jobs/JGEFS_ATMOS_GEMPAK_META
--- a/jobs/JGEFS_ATMOS_GEMPAK_META
+++ b/jobs/JGEFS_ATMOS_GEMPAK_META
@@ -4,8 +4,8 @@ echo "$(date -u) begin $(basename $BASH_SOURCE)"
 
 set -xa
 if [[ ${STRICT:-NO} == "YES" ]]; then
-	# Turn on strict bash error checking
-	set -eu
+  # Turn on strict bash error checking
+  set -eu
 fi
 export PS4='$SECONDS + $(basename $(basename $BASH_SOURCE))[$LINENO] '
 
@@ -79,12 +79,12 @@ export COMOUT=${COMOUT:-$(compath.py -o $NET/${ver})/${RUN}.${PDY}/$cyc}
 configs="gefs gefs_gempak_meta"
 config_path=$PARMgefs
 for config in $configs; do
-    . $config_path/$config.parm
-    export err=$?
-    if [[ $err != 0 ]]; then
-        echo "FATAL ERROR in $(basename $BASH_SOURCE): Error while loading parm file $config_path/$config.parm"
-        exit $err
-    fi
+  . $config_path/$config.parm
+  export err=$?
+  if [[ $err != 0 ]]; then
+    echo "FATAL ERROR in $(basename $BASH_SOURCE): Error while loading parm file $config_path/$config.parm"
+    exit $err
+  fi
 done
 
 export COMINsgfs=${COMINsgfs:-$(compath.py $envir/com/gfs/${gfs_ver})}
@@ -105,10 +105,10 @@ env | sort
 $HOMEgefs/scripts/exgefs_atmos_gempak_meta.sh
 export err=$?
 if [[ $err == 0 ]]; then
-    echo "$job completed normally!"
+  echo "$job completed normally!"
 else
-    echo "FATAL ERROR in $(basename $BASH_SOURCE): $job failed!"
-    exit $err
+  echo "FATAL ERROR in $(basename $BASH_SOURCE): $job failed!"
+  exit $err
 fi
 #############################################################
 
diff --git a/jobs/JGEFS_ATMOS_POST_CLEANUP b/jobs/JGEFS_ATMOS_POST_CLEANUP
--- a/jobs/JGEFS_ATMOS_POST_CLEANUP
+++ b/jobs/JGEFS_ATMOS_POST_CLEANUP
@@ -12,8 +12,8 @@ echo "$(date -u) begin ${.sh.file}"
 
 set -xa
 if [[ ${STRICT:-NO} == "YES" ]]; then
-	# Turn on strict bash error checking
-	set -eu
+  # Turn on strict bash error checking
+  set -eu
 fi
 export PS4='$SECONDS + $(basename ${.sh.file})[$LINENO] '
 
@@ -67,13 +67,13 @@ export PARMgefs=${PARMgefs:-$HOMEgefs/parm}
 ##############################################
 ver=${ver:-$(echo ${gefs_ver}|cut -c1-5)}
 if [ $cyc = 00 ]; then
-    export COMIN=${COMIN:-$(compath.py $envir/com/$NET/${ver})/${RUN}.${PDYm1}/$cyc}
-    export COMOUT=${COMOUT:-$(compath.py -o $NET/${ver})/${RUN}.${PDYm1}/$cyc}
-    export GESOUT=${GESOUT:-$(compath.py -o $NET/${ver})/${RUN}.${PDYm1}/$cyc/nwges}
+  export COMIN=${COMIN:-$(compath.py $envir/com/$NET/${ver})/${RUN}.${PDYm1}/$cyc}
+  export COMOUT=${COMOUT:-$(compath.py -o $NET/${ver})/${RUN}.${PDYm1}/$cyc}
+  export GESOUT=${GESOUT:-$(compath.py -o $NET/${ver})/${RUN}.${PDYm1}/$cyc/nwges}
 else
-    export COMIN=${COMIN:-$(compath.py $envir/com/$NET/${ver})/${RUN}.${PDY}/$cyc}
-    export COMOUT=${COMOUT:-$(compath.py -o $NET/${ver})/${RUN}.${PDY}/$cyc}
-    export GESOUT=${GESOUT:-$(compath.py $NET/${ver})/${RUN}.${PDY}/$cyc/nwges}
+  export COMIN=${COMIN:-$(compath.py $envir/com/$NET/${ver})/${RUN}.${PDY}/$cyc}
+  export COMOUT=${COMOUT:-$(compath.py -o $NET/${ver})/${RUN}.${PDY}/$cyc}
+  export GESOUT=${GESOUT:-$(compath.py $NET/${ver})/${RUN}.${PDY}/$cyc/nwges}
 fi
 
 ##############################################
@@ -82,12 +82,12 @@ echo set parameters using gefs.parm
 configs="gefs"
 config_path=$PARMgefs
 for config in $configs; do
-    . $config_path/$config.parm
-    export err=$?
-    if [[ $err != 0 ]]; then
-        echo "FATAL ERROR in ${.sh.file}: Error while loading parm file $config_path/$config.parm"
-        exit $err
-    fi
+  . $config_path/$config.parm
+  export err=$?
+  if [[ $err != 0 ]]; then
+    echo "FATAL ERROR in ${.sh.file}: Error while loading parm file $config_path/$config.parm"
+    exit $err
+  fi
 done
 export COMPONENT="atmos"
 
@@ -99,10 +99,10 @@ env | sort
 $HOMEgefs/scripts/exgefs_atmos_post_cleanup.sh
 export err=$?
 if [[ $err == 0 ]]; then
-    echo "$job completed normally!"
+  echo "$job completed normally!"
 else
-    echo "FATAL ERROR in ${.sh.file}: $job failed!"
-    exit $err
+  echo "FATAL ERROR in ${.sh.file}: $job failed!"
+  exit $err
 fi
 #############################################################
 
diff --git a/jobs/JGEFS_ATMOS_PRDGEN b/jobs/JGEFS_ATMOS_PRDGEN
--- a/jobs/JGEFS_ATMOS_PRDGEN
+++ b/jobs/JGEFS_ATMOS_PRDGEN
@@ -4,8 +4,8 @@ echo "$(date -u) begin ${.sh.file}"
 
 set -xa
 if [[ ${STRICT:-NO} == "YES" ]]; then
-	# Turn on strict bash error checking
-	set -eu
+  # Turn on strict bash error checking
+  set -eu
 fi
 export PS4='$SECONDS + $(basename ${.sh.file})[$LINENO] '
 
@@ -56,8 +56,8 @@ setpdy.sh
 source PDY
 
 if [ ${FORECAST_SEGMENT:-hr} = lr ]; then
-    export cyc=00
-    export cycle=t${cyc}z
+  export cyc=00
+  export cycle=t${cyc}z
 fi
 
 ####################################
@@ -77,9 +77,9 @@ export mem=$(echo $RUNMEM|cut -c3-5)
 export COMIN=${COMIN:-$(compath.py $envir/com/$NET/${ver})/${RUN}.${PDY}/$cyc}
 export COMOUT=${COMOUT:-$(compath.py -o $NET/${ver})/${RUN}.${PDY}/$cyc}
 if [[ ${NewCOM:-"YES"} == "YES" ]]; then
-    export mem=$(echo $RUNMEM|cut -c3-5)
-    export COMIN=${COMIN}/${mem}
-    export COMOUT=${COMOUT}/${mem}
+  export mem=$(echo $RUNMEM|cut -c3-5)
+  export COMIN=${COMIN}/${mem}
+  export COMOUT=${COMOUT}/${mem}
 fi
 
 #############################
@@ -88,18 +88,18 @@ fi
 configs="gefs gefs_prdgen"
 config_path=$PARMgefs
 for config in $configs; do
-    . $config_path/$config.parm
-    export err=$?
-    if [[ $err != 0 ]]; then
-        echo "FATAL ERROR in ${.sh.file}: Error while loading parm file $config_path/$config.parm"
-        exit $err
-    fi
+  . $config_path/$config.parm
+  export err=$?
+  if [[ $err != 0 ]]; then
+    echo "FATAL ERROR in ${.sh.file}: Error while loading parm file $config_path/$config.parm"
+    exit $err
+  fi
 done
 
 export COMINgfs=${COMINgfs:-$(compath.py $envir/com/gfs/${gfs_ver})/gfs.${PDY}/$cyc/atmos}
 
 if [[ $cplchm = ".true." ]]; then
-    COMPONENT="chem"
+  COMPONENT="chem"
 fi
 export COMPONENT=${COMPONENT:-atmos}
 
@@ -111,10 +111,10 @@ env | sort
 source $HOMEgefs/scripts/exgefs_atmos_prdgen.sh
 export err=$?
 if [[ $err == 0 ]]; then
-    echo "$job completed normally!"
+  echo "$job completed normally!"
 else
-    echo "FATAL ERROR in ${.sh.file}: $job failed!"
-    exit $err
+  echo "FATAL ERROR in ${.sh.file}: $job failed!"
+  exit $err
 fi
 #############################################################
 
diff --git a/jobs/JGEFS_ATMOS_PREP b/jobs/JGEFS_ATMOS_PREP
--- a/jobs/JGEFS_ATMOS_PREP
+++ b/jobs/JGEFS_ATMOS_PREP
@@ -4,8 +4,8 @@ echo "$(date -u) begin $(basename $BASH_SOURCE)"
 
 set -xa
 if [[ ${STRICT:-NO} == "YES" ]]; then
-	# Turn on strict bash error checking
-	set -eu
+  # Turn on strict bash error checking
+  set -eu
 fi
 export PS4='$SECONDS + $(basename $(basename $BASH_SOURCE))[$LINENO] '
 
@@ -75,12 +75,12 @@ export COMPONENT="atmos"
 configs="gefs gefs_atmos_prep"
 config_path=$PARMgefs
 for config in $configs; do
-    . $config_path/$config.parm
-    export err=$?
-    if [[ $err != 0 ]]; then
-        echo "FATAL ERROR in $(basename $BASH_SOURCE): Error while loading parm file $config_path/$config.parm"
-        exit $err
-    fi
+  . $config_path/$config.parm
+  export err=$?
+  if [[ $err != 0 ]]; then
+    echo "FATAL ERROR in $(basename $BASH_SOURCE): Error while loading parm file $config_path/$config.parm"
+    exit $err
+  fi
 done
 
 export COMOUT=${COMOUT:-$(compath.py -o $NET/${ver})/${RUN}.${PDY}/$cyc}
@@ -99,10 +99,10 @@ env | sort
 $HOMEgefs/scripts/exgefs_atmos_prep.sh
 export err=$?
 if [[ $err == 0 ]]; then
-    echo "$job completed normally!"
+  echo "$job completed normally!"
 else
-    echo "FATAL ERROR in $(basename $BASH_SOURCE): $job failed!"
-    exit $err
+  echo "FATAL ERROR in $(basename $BASH_SOURCE): $job failed!"
+  exit $err
 fi
 #############################################################
 
