Modify J-job and some other scripts for WCOSS2 transition: For prod code/data structure changes 1) $COMROOT:     In its sub-structures $ver replaced prod in each J-job     $ver and ${ver_xxx} are added to parm/gefs.parm (xxx=gfs/cfs/ec/uk/na/nam)     In parm/gefs_prep_emissions.parm, $COMROOT lines are moved to J-job     In scripts/exgefs_forecast.sh, $COMROOT related lines moved to J-job 2) $DCOMROOT: prod is dropped from its sub-structures 3) $GESROOT structure is removed related directories are under $COMOUT 4) $DATAROOT, tmpnwprd is changed to tmp 5) $NWROOT is replaced by $PACKAGEROOT 6) Remove lines with $jlogfile in J-job files and one script file 7) parm/gefs_init.parm is simplified to remove legacy variables

diff --git a/jobs/JGEFS_ATMOS_INIT_RECENTER b/jobs/JGEFS_ATMOS_INIT_RECENTER
--- a/jobs/JGEFS_ATMOS_INIT_RECENTER
+++ b/jobs/JGEFS_ATMOS_INIT_RECENTER
@@ -1,19 +1,19 @@
-#!/bin/ksh -l
+#!/bin/ksh
 
-echo "$(date -u) begin ${0}"
+echo "$(date -u) begin ${.sh.file}"
 
 set -xa
 if [[ ${STRICT:-NO} == "YES" ]]; then
 	# Turn on strict bash error checking
 	set -eu
 fi
-export PS4='$SECONDS + $(basename ${0})[$LINENO] '
+export PS4='$SECONDS + $(basename ${.sh.file})[$LINENO] '
 
 ####################################
 # Determine Job Output Name on System
 ####################################
-export jobid=${jobid:-"$job.$PBS_JOBID"}
-export pgmout="OUTPUT.${PBS_JOBID}"
+export jobid=${jobid:-"$job.$LSB_JOBID"}
+export pgmout="OUTPUT.${LSB_JOBID}"
 export pgmerr=errfile
 
 ####################################
@@ -57,16 +57,17 @@ source PDY
 ####################################
 # Specify Execution Areas
 ####################################
-export HOMEgefs=${HOMEgefs:-${NWROOT}/gefs.${gefs_ver}}
+export HOMEgefs=${HOMEgefs:-${PACKAGEROOT}/gefs.${gefs_ver}}
 export PARMgefs=${PARMgefs:-$HOMEgefs/parm}
 
 ##############################################
 # Define COM directories
 ##############################################
+ver=${ver:-$(echo ${gefs_ver}|cut -c2-3)}
 export COMPONENT=atmos
-export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/$cyc/$COMPONENT}
-export GESIN=$GESROOT/${envir}/${RUN}.${PDY}/$cyc
-export GESOUT=$GESROOT/${envir}/${RUN}.${PDY}/$cyc
+export COMOUT=${COMOUT:-${COMROOT}/${NET}/${ver}/${RUN}.${PDY}/$cyc/$COMPONENT}
+export GESIN=$COMROOT/${NET}/${ver}/${RUN}.${PDY}/$cyc/nwges
+export GESOUT=$COMROOT/${NET}/${ver}/${RUN}.${PDY}/$cyc/nwges
 
 #############################
 # Source relevant config files
@@ -77,12 +78,10 @@ for config in $configs; do
     . $config_path/$config.parm
     export err=$?
     if [[ $err != 0 ]]; then
-        echo "FATAL ERROR in ${0}: Error while loading parm file $config_path/$config.parm"
-        exit $err
+    	echo "FATAL ERROR in ${.sh.file}: Error while loading parm file $config_path/$config.parm"
+    	exit $err
     fi
 done
-
-export jlogfile=${jlogfile:-$DATA/jlogfile}
 
 echo "Environment before calling script"
 env | sort
@@ -94,7 +93,7 @@ export err=$?
 if [[ $err == 0 ]]; then
     echo "$job completed normally!"
 else
-    echo "FATAL ERROR in ${0}: $job failed!"
+    echo "FATAL ERROR in ${.sh.file}: $job failed!"
     exit $err
 fi
 #############################################################
@@ -105,6 +104,6 @@ fi
 cd $DATAROOT
 if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf $DATA ; fi
 
-echo "$(date -u) end ${0}"
+echo "$(date -u) end ${.sh.file}"
 
 exit $err
diff --git a/jobs/JGEFS_CHEM_PREP_EMISSIONS b/jobs/JGEFS_CHEM_PREP_EMISSIONS
--- a/jobs/JGEFS_CHEM_PREP_EMISSIONS
+++ b/jobs/JGEFS_CHEM_PREP_EMISSIONS
@@ -1,19 +1,19 @@
 #!/bin/bash
 
-echo "$(date -u) begin $(basename ${0})"
+echo "$(date -u) begin $(basename $BASH_SOURCE)"
 
 set -xa
 if [[ ${STRICT:-NO} == "YES" ]]; then
 	# Turn on strict bash error checking
 	set -eu
 fi
-export PS4='$SECONDS + $(basename ${0}))[$LINENO] '
+export PS4='$SECONDS + $(basename $BASH_SOURCE))[$LINENO] '
 
 ####################################
 # Determine Job Output Name on System
 ####################################
-export jobid=${jobid:-"$job.$PBS_JOBID"}
-export pgmout="OUTPUT.${PBS_JOBID}"
+export jobid=${jobid:-"$job.$LSB_JOBID"}
+export pgmout="OUTPUT.${LSB_JOBID}"
 export pgmerr=errfile
 
 ####################################
@@ -51,14 +51,15 @@ source PDY
 ####################################
 # Specify Execution Areas
 ####################################
-export HOMEgefs=${HOMEgefs:-${NWROOT}/gefs.${gefs_ver}}
+export HOMEgefs=${HOMEgefs:-${PACKAGEROOT}/gefs.${gefs_ver}}
 export PARMgefs=${PARMgefs:-$HOMEgefs/parm}
 
 ##############################################
 # Define COM directories
 ##############################################
+ver=${ver:-$(echo ${gefs_ver}|cut -c2-3)}
 export COMPONENT=chem
-export GESOUT=$GESROOT/${envir}/${RUN}.${PDY}/$cyc
+export GESOUT=$COMROOT/${NET}/${ver}/${RUN}.${PDY}/$cyc/nwges
 mkdir -p $GESOUT
 
 #############################
@@ -70,12 +71,17 @@ for config in $configs; do
     . $config_path/$config.parm
     export err=$?
     if [[ $err != 0 ]]; then
-        echo "FATAL ERROR in $(basename ${0}): Error while loading parm file $config_path/$config.parm"
-        exit $err
+    	echo "FATAL ERROR in $(basename $BASH_SOURCE): Error while loading parm file $config_path/$config.parm"
+    	exit $err
     fi
 done
 
-export jlogfile=${jlogfile:-$DATA/jlogfile}
+export GBBEPX_DATA_DIR_TODAY=${GBBEPX_DATA_DIR_TODAY:-$DCOMROOT/$PDY/firewx}
+export GBBEPX_DATA_DIR_YESTERDAY=${GBBEPX_DATA_DIR_YESTERDAY:-$DCOMROOT/$PDYm1/firewx}
+export BBEM_MODIS_DIR_TODAY=${BBEM_MODIS_DIR_TODAY:-$DCOMROOT/$PDY/modis_fire}
+export BBEM_MODIS_DIR_YESTERDAY=${BBEM_MODIS_DIR_YESTERDAY:-$DCOMROOT/$PDYm1/modis_fire}
+export BBEM_WFABBA_DIR_TODAY=${BBEM_WFABBA_DIR_TODAY:-$DCOMROOT/$PDY/wf_abba}
+export BBEM_WFABBA_DIR_YESTERDAY=${BBEM_WFABBA_DIR_YESTERDAY:-$DCOMROOT/$PDYm1/wf_abba}
 
 echo "Environment before calling script"
 env | sort
@@ -87,7 +93,7 @@ export err=$?
 if [[ $err == 0 ]]; then
     echo "$job completed normally!"
 else
-    echo "FATAL ERROR in $(basename ${0}): $job failed!"
+    echo "FATAL ERROR in $(basename $BASH_SOURCE): $job failed!"
     exit $err
 fi
 #############################################################
@@ -98,6 +104,6 @@ fi
 cd $DATAROOT
 if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf $DATA ; fi
 
-echo "$(date -u) end $(basename ${0})"
+echo "$(date -u) end $(basename $BASH_SOURCE)"
 
 exit $err
