Change to use new COM
 On branch feature/v13_atmos_prdgen
	modified:   jobs/JGEFS_ATMOS_PRDGEN
	modified:   parm/config/config.prdgen

Refs: #98

diff --git a/jobs/JGEFS_ATMOS_PRDGEN b/jobs/JGEFS_ATMOS_PRDGEN
--- a/jobs/JGEFS_ATMOS_PRDGEN
+++ b/jobs/JGEFS_ATMOS_PRDGEN
@@ -1,18 +1,11 @@
-#!/bin/ksh
+#! /usr/bin/env bash
 
-echo "$(date -u) begin ${.sh.file}"
-
-set -xa
-if [[ ${STRICT:-NO} == "YES" ]]; then
-	# Turn on strict bash error checking
-	set -eu
-fi
-export PS4='$SECONDS + $(basename ${.sh.file})[$LINENO] '
+source "${HOMEgefs:-${HOMEgfs}}/ush/preamble.sh"
 
 ####################################
 # Determine Job Output Name on System
 ####################################
-export jobid=${jobid:-"$job.$PBS_JOBID"}
+export jobid=${jobid:-"${job}.${PBS_JOBID}"}
 export pgmout="OUTPUT.${PBS_JOBID}"
 export pgmerr=errfile
 
@@ -56,68 +49,91 @@ setpdy.sh
 source PDY
 
 if [ ${FORECAST_SEGMENT:-hr} = lr ]; then
-    export cyc=00
-    export cycle=t${cyc}z
+  export cyc=00
+  export cycle=t${cyc}z
 fi
 
 ####################################
 # Specify Execution Areas
 ####################################
 export HOMEgefs=${HOMEgefs:-${PACKAGEROOT}/gefs.${gefs_ver}}
-export EXECgefs=${EXECgefs:-$HOMEgefs/exec}
-export USHgefs=${USHgefs:-$HOMEgefs/ush}
-export FIXgefs=${FIXgefs:-$HOMEgefs/fix/fix_gefs}
-export PARMgefs=${PARMgefs:-$HOMEgefs/parm}
-
-##############################################
-# Define COM directories
-##############################################
-ver=${ver:-$(echo ${gefs_ver}|cut -c1-5)}
-export COMIN=${COMIN:-$(compath.py $envir/com/$NET/${ver})/${RUN}.${PDY}/$cyc}
-export COMOUT=${COMOUT:-$(compath.py -o $NET/${ver})/${RUN}.${PDY}/$cyc}
+export PARMgefs=${PARMgefs:-${HOMEgefs}/parm}
+export EXECgefs=${EXECgefs:-${HOMEgefs}/exec}
+export USHgefs=${USHgefs:-${HOMEgefs}/ush}
 
 #############################
 # Source relevant config files
 #############################
-configs="gefs gefs_prdgen"
-config_path=$PARMgefs
-for config in $configs; do
-    . $config_path/$config.parm
-    export err=$?
-    if [[ $err != 0 ]]; then
-        echo "FATAL ERROR in ${.sh.file}: Error while loading parm file $config_path/$config.parm"
-        exit $err
-    fi
+#export CDATE=$PDY$cyc
+configs="base prdgen"
+config_path=${PARMgefs}/config
+for config in ${configs}; do
+  . ${config_path}/config.${config}
+  export err=$?
+  if [[ $err != 0 ]]; then
+    echo "FATAL ERROR in ${BASH_SOURCE[0]}: Error while loading parm file ${config_path}/config.${config}"
+    exit $err
+  fi
 done
 
-export COMINgfs=${COMINgfs:-$(compath.py $envir/com/gfs/${gfs_ver})/gfs.${PDY}/$cyc/atmos}
+##############################################
+# Define COM directories
+##############################################
+ver=${gefs_ver:0:5}
+export ROTDIR=${ROTDIR:-$(compath.py ${envir}/com/${NET}/${ver})}
+export ROTDIR_GFS=${ROTDIR_GFS:-$(compath.py ${envir}/com/gfs/${gfs_ver})}
 
 if [[ $cplchm = ".true." ]]; then
     COMPONENT="chem"
 fi
+
 export COMPONENT=${COMPONENT:-atmos}
 
 echo "Environment before calling script"
 env | sort
 
+# Construct COM variables from templates (see config.com)
+
+declare -rx memchar=${RUNMEM}
+
+MEMDIR="${memchar}" YMD=${PDY} HH=${cyc} generate_com -rx COM_ATMOS_HISTORY COM_ATMOS_MASTER
+
+export PRDGEN_STREAMS="res_2p50 res_0p50 res_0p25_s1 res_0p25_s2"
+
+if [[ ${RUNMEM} == "memgfs" ]]; then
+  grids=['2p50' '0p25' '0p25s' '0p50a' '0p50b']
+elif [[ ${RUNMEM} == "memaer" ]]; then
+  grids=['0p25' '0p25s' '0p50a' '0p50b']
+else
+  if [ ${FORECAST_SEGMENT} = lr ]; then
+    grids=['2p50' '0p50a' '0p50b']
+  else
+    grids=['2p50' '0p25' '0p25s' '0p50a' '0p50b']
+  fi
+fi
+
+for grid in ${grids}; do
+  prod_dir="COM_ATMOS_GRIB_${grid}"
+  MEMDIR="${memchar}" GRID=${grid} YMD=${PDY} HH=${cyc} generate_com -rx "${prod_dir}:COM_ATMOS_GRIB_TMPL"
+  if [[ ! -d "${prod_dir}" ]]; then mkdir -m 775 -p "${!prod_dir}"; fi
+done
+
 #############################################################
 # Execute the script
-source $HOMEgefs/scripts/exgefs_atmos_prdgen.sh
+#source $HOMEgefs/scripts/exgefs_atmos_prdgen.sh
 export err=$?
 if [[ $err == 0 ]]; then
-    echo "$job completed normally!"
+  echo "${job} completed normally!"
 else
-    echo "FATAL ERROR in ${.sh.file}: $job failed!"
-    exit $err
+  echo "FATAL ERROR in ${BASH_SOURCE[0]}: ${job} failed!"
+  exit ${err}
 fi
 #############################################################
 
 ##############################
 # Remove the Temporary working directory
 ##############################
-cd $DATAROOT
-if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf $DATA ; fi
-
-echo "$(date -u) end ${.sh.file}"
+cd ${DATAROOT}
+if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf ${DATA} ; fi
 
 exit $err
